LocalDate and Instant parsers
scala-js/scala-js-java-time pull request #36
Opened 2017-11-16 02:04 UTC by chrisshafer

- Implemented `parse` method for `java.time.Instant`
- Implemented `parse` method for `java.time.LocalDate`
- Fixed bug with `toString` method in `java.time.Instant`

Fixes: https://github.com/scala-js/scala-js-java-time/issues/35

2017-11-16 02:06 UTC, chrisshafer commented
Hi! I wasn't quite sure what path to take when implementing the parsing functionality. Please let me know if this is not the right approach.

2017-11-16 09:44 UTC, sjrd commented
Thank you for your contribution.

Before I take a look at your PR, could you please confirm that you did *not* look at the source code of `java.time` of OpenJDK nor OracleJDK? See https://github.com/scala-js/scala-js-java-time/blob/master/CONTRIBUTING.md

2017-11-16 16:06 UTC, chrisshafer commented
Of Course!
 I did not look at the source code of `java.time` of either OpenJDK or OracleJDK.

2017-12-16 21:12 UTC, chrisshafer commented
@sjrd Would it be possible to get a review please 😄 ?

2017-12-17 09:03 UTC, sjrd commented
Ah sorry, I forgot about this. I'll try to fit it sometime this week.

2018-01-15 04:08 UTC, chrisshafer commented
Sorry, this got closed by a bad reference.

2018-01-16 16:07 UTC, sjrd requested changes
Thanks. I have finally found some time for this.

I have a few comments, mostly coding style things. I have only reported each kind of coding style issue once, so make sure to look for other places in your PR where the same comments apply.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +      case years => years.toString
We typically do not use `match` constructs for what would otherwise be a chain an if/else chain. The style would be more like:
```scala
val years = hi * 10000 + date.getYear
val yearSegment = {
  if (years > 9999) s"+$years"
  else if (years < 0 && years > -1000) "-%04d".format(-years)
  else years.toString
}
```
(also, `Math.abs(years)` is advantageously replaced by `-years` since we already it is `< 0` at that point)

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    val daySegment    = "%02d".format(date.getDayOfMonth)
In our coding style, we do not use vertical alignment (except for arrows of single-line `case`s).

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
>    /*
Missing blank line above this line.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    )
Coding style: either
```scala
    Try(segment.toInt).getOrElse {
      throw new DateTimeParseException(s"$segment is not a valid $classifier")
    }
```
or
```scala
    Try(segment.toInt).getOrElse(
        throw new DateTimeParseException(s"$segment is not a valid $classifier"))
```

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    if(monthDay.getMonth == Month.FEBRUARY && leapYear) {
Coding style: space between `if` and `(`

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +      LocalDate.of(extremeLeapYear * -1, month, day).toEpochDay - epochDaysToAccountForExtreme
`extremeLeapYear * -1` -> `-extremLeapYear`

Also, coding style: do not use `{}` if all the branches of the if/else if/else branch stand on one line.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    }
I don't really understand why we need this dance with `Min/MaxYear` and `extremeLeapYear`. Why doesn't the last branch work for `MinYear` and `MaxYear`?

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +
2 spurious blank lines.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +      = text
Now that's a style I've never seen before :p

We use:
```scala
      val pattern(sign, yearSegment, monthSegment, daySegment,
          hourSegment, minutesSegment, secondsSegment, nanosecondsSegment) = text
```

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +      case Success(success)                     => success
Don't use a `Try {}` block only to `match` on it right after. That is uselessly inefficient.

Prefer a `try {} catch {}` in that case.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +          secondsOffset
Coding style: we do not indent subsequent lines when they are linked by a binary operator. Instead, write:
```scala
      val epochSecondsOffset = {
        dayOffset * SECONDS_IN_DAY +
        hourOffset * SECONDS_IN_HOUR +
        minuteOffset * SECONDS_IN_MINUTE +
        secondsOffset
      }
```

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +  private def handleSegmentParse(segment: String)(classifier: String) = {
Consider the simpler name `parseSegment` for this method.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/format/DateTimeParseException.scala
> +  def this(message: String) = this(message, null, Int.MinValue, null)
This constructor does not exist in the JavaDoc: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeParseException.html

You should follow the specification of the JavaDoc for all public members that you choose to implement, and not add any other public member.

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/format/DateTimeParseException.scala
> +  //def getParsedString(): String = parsedData.toString
I see no reason not to implement those trivial methods.

2018-01-16 16:07 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/InstantTest.scala
> +
Double blank line.

2018-01-16 16:07 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/LocalDateTest.scala
> +
Spurious blank line.

2018-01-16 16:07 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/LocalDateTest.scala
> +
I feel like this is under-tested. For example, I would definitely want to see exceptional cases for non-digits, for Feb 29 on a non-leap year, and stuff like that.

2018-01-16 16:07 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/InstantTest.scala
> +  }
The exceptional cases are under-tested here too. For example, what about `...T24:...` or `T13:65:...`?

2018-01-16 16:07 UTC, sjrd commented on src/main/scala/java/time/LocalDate.scala
> +    val potentialLocalDate = Try {
Similar comments as those for `Instant.parse()` apply here.

2018-01-16 16:07 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/InstantTest.scala
> +
You should also test one non-String `CharSequence`, e.g., a `java.nio.CharBuffer.wrap(...)`. Same in `LocalDateTest`.

2018-02-07 21:33 UTC, chrisshafer commented on src/main/scala/java/time/Instant.scala
> +      = text
Neither have I until now haha. Thats really bad, thanks for the catch.

2018-02-07 21:35 UTC, chrisshafer commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/LocalDateTest.scala
> +
Indeed! In fact it looks like the previous version wouldn't catch the case of a Fed 29 on a non-leap year.

2018-02-07 22:00 UTC, chrisshafer commented
Hey @sjrd Thanks for the review! Let me know if there is anything else I missed!

2018-02-09 13:05 UTC, sjrd requested changes
Thanks. I have a couple more comments.

As I'm leaving on vacation for 3 weeks starting tomorrow, I probably won't have time to look at this PR again before the week of March 5-9.

2018-02-09 13:05 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    println(years)
Leftover printlns :)

2018-02-09 13:05 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    println(yearSegment)
Another one here.

2018-02-09 13:05 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
>    /*
Still relevant.

2018-02-09 13:05 UTC, sjrd commented on testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/LocalDateTest.scala
> +//    expectThrows(classOf[DateTimeParseException], parse("2012-01-34"))
Why are those commented out?

2018-02-09 13:05 UTC, sjrd commented on src/main/scala/java/time/Instant.scala
> +    }
The question still stands ;)

2018-02-09 15:27 UTC, chrisshafer commented on src/main/scala/java/time/Instant.scala
> +    println(years)
Oh my... Sorry I totally missed these.

2018-02-09 15:31 UTC, chrisshafer commented
Ok, thanks for the heads up!

2018-02-09 15:45 UTC, chrisshafer commented on src/main/scala/java/time/Instant.scala
> +    }
Sorry, the extreme leap year thing is to account for the fact that Instant.MAX is `+1000000000-12-31T23:59:59.999999999Z` and LocalDate.MAX is `+999999999-12-31`. 

To be honest I don't remember why I chose this Impl over "LocalDate.MAX.epochDays" + "epochDays from Instant.MAX by year". Ill see what I can do to make it more clear what is going on!

2018-03-28 19:43 UTC, sjrd approved these changes
Thanks for the updates. I've reformatted the code for you, so that it's good to merge, now.

2018-03-28 19:44 UTC, merged